sudo: false    # Use container-based infrastructure
language: python

matrix:
    include:
    - python: 2.7
      env:
        - PYTHON_VERSION="2.7"
        - NOSE_ARGS="-v --with-cov --cov pyradarmet pyradarmet"
        - COVERALLS="true"
    - python: 2.7
      env:
        - PYTHON_VERSION="2.7"
        - NOSE_ARGS="-v --with-cov --cov pyradarmet --exe pyradarmet"
        - FROM_RECIPE="true"
        - DOC_BUILD="true"
    - python: 3.4
      env:
        - PYTHON_VERSION="3.4"
        - NOSE_ARGS="-v --with-cov --cov pyradarmet pyradarmet"
    - python: 3.5
      env:
        - PYTHON_VERSION="3.5"
        - NOSE_ARGS="-v --with-cov --cov pyradarmet pyradarmet"
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
        - NOSE_ARGS="-v --with-cov --cov pyradarmet pyradarmet"
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script: eval xvfb-run nosetests $NOSE_ARGS
after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    - if [[ "$COVERALLS" == "true" ]]; then coveralls || echo "failed"; fi
    # Build docs if requested
- if [[ "$DOC_BUILD" == "true" ]]; then cd $TRAVIS_BUILD_DIR; source continuous_integration/build_docs.sh; fi
